name: 'Secret Scanning Review'
on: [pull_request]

jobs:
  secret-scanning-review:
    runs-on: [self-hosted, solinas-medium, solinas-ubuntu_22_04]
    steps:
      - name: 'Secret Scanning Review Action'
        uses: b1-build/secret-scanning-review-action@main
        with:
          token: ${{ secrets.B1_GITHUB_TOKEN }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python'
