name: 'Secret Scanning Review'
on: 
  pull_request:
  workflow_run:
    workflows: ["Secret Scanning"]
    types: [completed]

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v2.2.0
        with:
          token: ${{ secrets.B1_GITHUB_TOKEN }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python'
